Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\run_training.py", line 133, in <module>
    main(args.lp, args.rf)
  File "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\run_training.py", line 34, in main
    run_training(config=config, mode='pretrain', run_folder=run_folder)
  File "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\run_training.py", line 112, in run_training
    metrics = trainer.train()
              ^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\training\trainer.py", line 112, in train
    train_loss = self.train_epoch()
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\OneDrive\DSML\Project\thesis-repo\sms\exp1\training\trainer.py", line 89, in train_epoch
    for batch in self.train_loader:
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\dataloader.py", line 1344, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\dataloader.py", line 1370, in _process_data
    data.reraise()
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\_utils.py", line 706, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\worker.py", line 309, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 55, in fetch
    return self.collate_fn(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 317, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 174, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 174, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 142, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 223, in collate_numpy_array_fn
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\cunn2\miniconda3\envs\sms\Lib\site-packages\torch\utils\data\_utils\collate.py", line 223, in <listcomp>
    return collate([torch.as_tensor(b) for b in batch], collate_fn_map=collate_fn_map)
                    ^^^^^^^^^^^^^^^^^^
ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().)